// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: stories.proto

package stories

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "mpb/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoriesService_CreateStory_FullMethodName = "/stories.StoriesService/CreateStory"
	StoriesService_GetStory_FullMethodName    = "/stories.StoriesService/GetStory"
	StoriesService_ListStories_FullMethodName = "/stories.StoriesService/ListStories"
	StoriesService_DeleteStory_FullMethodName = "/stories.StoriesService/DeleteStory"
)

// StoriesServiceClient is the client API for StoriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoriesServiceClient interface {
	CreateStory(ctx context.Context, in *CreateStoryRequest, opts ...grpc.CallOption) (*StoryResponse, error)
	GetStory(ctx context.Context, in *GetStoryRequest, opts ...grpc.CallOption) (*StoryResponse, error)
	ListStories(ctx context.Context, in *ListStoriesRequest, opts ...grpc.CallOption) (*ListStoriesResponse, error)
	DeleteStory(ctx context.Context, in *DeleteStoryRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type storiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoriesServiceClient(cc grpc.ClientConnInterface) StoriesServiceClient {
	return &storiesServiceClient{cc}
}

func (c *storiesServiceClient) CreateStory(ctx context.Context, in *CreateStoryRequest, opts ...grpc.CallOption) (*StoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoryResponse)
	err := c.cc.Invoke(ctx, StoriesService_CreateStory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storiesServiceClient) GetStory(ctx context.Context, in *GetStoryRequest, opts ...grpc.CallOption) (*StoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoryResponse)
	err := c.cc.Invoke(ctx, StoriesService_GetStory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storiesServiceClient) ListStories(ctx context.Context, in *ListStoriesRequest, opts ...grpc.CallOption) (*ListStoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStoriesResponse)
	err := c.cc.Invoke(ctx, StoriesService_ListStories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storiesServiceClient) DeleteStory(ctx context.Context, in *DeleteStoryRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, StoriesService_DeleteStory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoriesServiceServer is the server API for StoriesService service.
// All implementations must embed UnimplementedStoriesServiceServer
// for forward compatibility.
type StoriesServiceServer interface {
	CreateStory(context.Context, *CreateStoryRequest) (*StoryResponse, error)
	GetStory(context.Context, *GetStoryRequest) (*StoryResponse, error)
	ListStories(context.Context, *ListStoriesRequest) (*ListStoriesResponse, error)
	DeleteStory(context.Context, *DeleteStoryRequest) (*common.Empty, error)
	mustEmbedUnimplementedStoriesServiceServer()
}

// UnimplementedStoriesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoriesServiceServer struct{}

func (UnimplementedStoriesServiceServer) CreateStory(context.Context, *CreateStoryRequest) (*StoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStory not implemented")
}
func (UnimplementedStoriesServiceServer) GetStory(context.Context, *GetStoryRequest) (*StoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStory not implemented")
}
func (UnimplementedStoriesServiceServer) ListStories(context.Context, *ListStoriesRequest) (*ListStoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStories not implemented")
}
func (UnimplementedStoriesServiceServer) DeleteStory(context.Context, *DeleteStoryRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStory not implemented")
}
func (UnimplementedStoriesServiceServer) mustEmbedUnimplementedStoriesServiceServer() {}
func (UnimplementedStoriesServiceServer) testEmbeddedByValue()                        {}

// UnsafeStoriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoriesServiceServer will
// result in compilation errors.
type UnsafeStoriesServiceServer interface {
	mustEmbedUnimplementedStoriesServiceServer()
}

func RegisterStoriesServiceServer(s grpc.ServiceRegistrar, srv StoriesServiceServer) {
	// If the following call pancis, it indicates UnimplementedStoriesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoriesService_ServiceDesc, srv)
}

func _StoriesService_CreateStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoriesServiceServer).CreateStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoriesService_CreateStory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoriesServiceServer).CreateStory(ctx, req.(*CreateStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoriesService_GetStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoriesServiceServer).GetStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoriesService_GetStory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoriesServiceServer).GetStory(ctx, req.(*GetStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoriesService_ListStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoriesServiceServer).ListStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoriesService_ListStories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoriesServiceServer).ListStories(ctx, req.(*ListStoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoriesService_DeleteStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoriesServiceServer).DeleteStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoriesService_DeleteStory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoriesServiceServer).DeleteStory(ctx, req.(*DeleteStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoriesService_ServiceDesc is the grpc.ServiceDesc for StoriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stories.StoriesService",
	HandlerType: (*StoriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStory",
			Handler:    _StoriesService_CreateStory_Handler,
		},
		{
			MethodName: "GetStory",
			Handler:    _StoriesService_GetStory_Handler,
		},
		{
			MethodName: "ListStories",
			Handler:    _StoriesService_ListStories_Handler,
		},
		{
			MethodName: "DeleteStory",
			Handler:    _StoriesService_DeleteStory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stories.proto",
}
