// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: stories.proto

package stories

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "mpb/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Story struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,3,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Story) Reset() {
	*x = Story{}
	mi := &file_stories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{0}
}

func (x *Story) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Story) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Story) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Story) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Story) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type CreateStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryRequest) Reset() {
	*x = CreateStoryRequest{}
	mi := &file_stories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryRequest) ProtoMessage() {}

func (x *CreateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryRequest.ProtoReflect.Descriptor instead.
func (*CreateStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateStoryRequest) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

type GetStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       int32                  `protobuf:"varint,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryRequest) Reset() {
	*x = GetStoryRequest{}
	mi := &file_stories_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryRequest) ProtoMessage() {}

func (x *GetStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryRequest.ProtoReflect.Descriptor instead.
func (*GetStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{2}
}

func (x *GetStoryRequest) GetStoryId() int32 {
	if x != nil {
		return x.StoryId
	}
	return 0
}

type ListStoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoriesRequest) Reset() {
	*x = ListStoriesRequest{}
	mi := &file_stories_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoriesRequest) ProtoMessage() {}

func (x *ListStoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoriesRequest.ProtoReflect.Descriptor instead.
func (*ListStoriesRequest) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{3}
}

func (x *ListStoriesRequest) GetUserId() int32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ListStoriesRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DeleteStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       int32                  `protobuf:"varint,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoryRequest) Reset() {
	*x = DeleteStoryRequest{}
	mi := &file_stories_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoryRequest) ProtoMessage() {}

func (x *DeleteStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteStoryRequest) GetStoryId() int32 {
	if x != nil {
		return x.StoryId
	}
	return 0
}

func (x *DeleteStoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type StoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Story         *Story                 `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryResponse) Reset() {
	*x = StoryResponse{}
	mi := &file_stories_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryResponse) ProtoMessage() {}

func (x *StoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryResponse.ProtoReflect.Descriptor instead.
func (*StoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{5}
}

func (x *StoryResponse) GetStory() *Story {
	if x != nil {
		return x.Story
	}
	return nil
}

type ListStoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stories       []*Story               `protobuf:"bytes,1,rep,name=stories,proto3" json:"stories,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoriesResponse) Reset() {
	*x = ListStoriesResponse{}
	mi := &file_stories_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoriesResponse) ProtoMessage() {}

func (x *ListStoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoriesResponse.ProtoReflect.Descriptor instead.
func (*ListStoriesResponse) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{6}
}

func (x *ListStoriesResponse) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

func (x *ListStoriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_stories_proto protoreflect.FileDescriptor

const file_stories_proto_rawDesc = "" +
	"\n" +
	"\rstories.proto\x12\astories\x1a\fcommon.proto\"\x8b\x01\n" +
	"\x05Story\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tmedia_url\x18\x03 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\"J\n" +
	"\x12CreateStoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\",\n" +
	"\x0fGetStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\x05R\astoryId\"r\n" +
	"\x12ListStoriesRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x05H\x00R\x06userId\x88\x01\x01\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"paginationB\n" +
	"\n" +
	"\b_user_id\"H\n" +
	"\x12DeleteStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\x05R\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"5\n" +
	"\rStoryResponse\x12$\n" +
	"\x05story\x18\x01 \x01(\v2\x0e.stories.StoryR\x05story\"U\n" +
	"\x13ListStoriesResponse\x12(\n" +
	"\astories\x18\x01 \x03(\v2\x0e.stories.StoryR\astories\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x97\x02\n" +
	"\x0eStoriesService\x12B\n" +
	"\vCreateStory\x12\x1b.stories.CreateStoryRequest\x1a\x16.stories.StoryResponse\x12<\n" +
	"\bGetStory\x12\x18.stories.GetStoryRequest\x1a\x16.stories.StoryResponse\x12H\n" +
	"\vListStories\x12\x1b.stories.ListStoriesRequest\x1a\x1c.stories.ListStoriesResponse\x129\n" +
	"\vDeleteStory\x12\x1b.stories.DeleteStoryRequest\x1a\r.common.EmptyB\x13Z\x11mpb/proto/storiesb\x06proto3"

var (
	file_stories_proto_rawDescOnce sync.Once
	file_stories_proto_rawDescData []byte
)

func file_stories_proto_rawDescGZIP() []byte {
	file_stories_proto_rawDescOnce.Do(func() {
		file_stories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stories_proto_rawDesc), len(file_stories_proto_rawDesc)))
	})
	return file_stories_proto_rawDescData
}

var file_stories_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stories_proto_goTypes = []any{
	(*Story)(nil),               // 0: stories.Story
	(*CreateStoryRequest)(nil),  // 1: stories.CreateStoryRequest
	(*GetStoryRequest)(nil),     // 2: stories.GetStoryRequest
	(*ListStoriesRequest)(nil),  // 3: stories.ListStoriesRequest
	(*DeleteStoryRequest)(nil),  // 4: stories.DeleteStoryRequest
	(*StoryResponse)(nil),       // 5: stories.StoryResponse
	(*ListStoriesResponse)(nil), // 6: stories.ListStoriesResponse
	(*common.Pagination)(nil),   // 7: common.Pagination
	(*common.Empty)(nil),        // 8: common.Empty
}
var file_stories_proto_depIdxs = []int32{
	7, // 0: stories.ListStoriesRequest.pagination:type_name -> common.Pagination
	0, // 1: stories.StoryResponse.story:type_name -> stories.Story
	0, // 2: stories.ListStoriesResponse.stories:type_name -> stories.Story
	1, // 3: stories.StoriesService.CreateStory:input_type -> stories.CreateStoryRequest
	2, // 4: stories.StoriesService.GetStory:input_type -> stories.GetStoryRequest
	3, // 5: stories.StoriesService.ListStories:input_type -> stories.ListStoriesRequest
	4, // 6: stories.StoriesService.DeleteStory:input_type -> stories.DeleteStoryRequest
	5, // 7: stories.StoriesService.CreateStory:output_type -> stories.StoryResponse
	5, // 8: stories.StoriesService.GetStory:output_type -> stories.StoryResponse
	6, // 9: stories.StoriesService.ListStories:output_type -> stories.ListStoriesResponse
	8, // 10: stories.StoriesService.DeleteStory:output_type -> common.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stories_proto_init() }
func file_stories_proto_init() {
	if File_stories_proto != nil {
		return
	}
	file_stories_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stories_proto_rawDesc), len(file_stories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stories_proto_goTypes,
		DependencyIndexes: file_stories_proto_depIdxs,
		MessageInfos:      file_stories_proto_msgTypes,
	}.Build()
	File_stories_proto = out.File
	file_stories_proto_goTypes = nil
	file_stories_proto_depIdxs = nil
}
